import type { Metadata } from "next";
import Link from "next/link";
import type { ReactNode } from "react";
import { PageHero } from "@/components/page-hero";

export const metadata: Metadata = { title: "Privacy notice" };

export default function PrivacyPage() {
  return <><PageHero eyebrow="Your information" title="Website privacy notice" lede="How Terratora Limited collects, uses, protects and retains personal data when you use this website." image="/images/hero/reporting.jpg" imagePosition="50% 48%" crumbs={[{ label: "Privacy notice" }]} /><section className="policy-page" data-color-flow="clear"><div className="shell policy-grid"><aside><p>Data protection contact</p><a href="mailto:privacy@terratoraconsulting.com">privacy@terratoraconsulting.com</a></aside><div className="policy-copy">
    <Policy title="Overview"><p>This Privacy Notice explains how Terratora Limited collects and processes your personal data when you visit our website and related platforms (the “Site”). It sets out what we do with your personal data, how we keep it secure and the rights you have in relation to it.</p></Policy>
    <Policy title="Who we are"><p>Terratora Limited (“Terratora” or “the Company”) is an Environmental, Social and Governance advisory firm helping organisations in Nigeria and globally navigate evolving regulatory mandates, transform operations and create long-term stakeholder value. We may use your details strictly to evaluate business requirements, address enquiries and deliver strategic sustainability and corporate-transformation services.</p></Policy>
    <Policy title="Personal data we collect and process"><p>We limit collection to what is necessary to fulfil your request.</p><h3>Data you provide directly</h3><ul><li><strong>Contact and professional identifiers:</strong> Full name, corporate email address, phone number, job title or designation, and organisation name.</li><li><strong>Enquiry details:</strong> The content of your message, project brief or service request.</li><li><strong>Communication and marketing preferences:</strong> Your explicit preference about receiving regulatory briefs, industry insights or other promotional material.</li></ul><h3>Data collected automatically</h3><ul><li><strong>Usage and behavioural data:</strong> Pages viewed, resources downloaded, search queries and duration of visit.</li><li><strong>Technical and device identifiers:</strong> IP address, browser type, operating system, device characteristics and approximate geographic region.</li></ul></Policy>
    <Policy title="Cookies"><p>Cookies help us distinguish you from other users and provide an improved browsing experience. Read our <Link href="/cookies">Cookie Policy</Link> for further information.</p></Policy>
    <Policy title="Use of your personal data"><p>We may use personal data collected on our Site to:</p><ul><li>Respond to enquiries, service requests or consultative briefs submitted through forms or email links.</li><li>Manage and maintain our professional relationship with your organisation, including proposals, briefings and service delivery.</li><li>Improve website functionality, service offerings and overall user experience.</li><li>Send ESG industry insights, regulatory updates and corporate publications where you have explicitly opted in.</li><li>Comply with legal, regulatory and reporting obligations under Nigerian law, including NDPA requirements, or relevant international standards.</li></ul></Policy>
    <Policy title="Legal basis for processing"><ul><li><strong>Contractual necessity:</strong> Processing necessary to take pre-contractual steps at your request or execute an advisory agreement.</li><li><strong>Legitimate interests:</strong> Processing necessary to operate, secure and optimise the website, respond to business enquiries and conduct B2B communications, provided your rights do not override these interests.</li><li><strong>Explicit consent:</strong> Where required, including subscriptions to regulatory briefs or acceptance of optional cookies. You may withdraw consent at any time without penalty.</li><li><strong>Legal and regulatory obligations:</strong> Processing necessary to comply with legal, tax or regulatory duties under Nigerian law or international professional standards.</li></ul></Policy>
    <Policy title="Sharing of your personal data"><p>Terratora does not sell, rent or trade your personal data for marketing. We share information only under appropriate confidentiality arrangements and in compliance with the NDPA for the following purposes:</p><ul><li><strong>Third-party service providers and sub-processors:</strong> Vetted technical vendors such as cloud hosting, IT infrastructure, web analytics and client-management tools, acting only on our instructions.</li><li><strong>Professional advisers and affiliates:</strong> Legal advisers, auditors or technical co-consultants where needed for specialised or multi-jurisdictional engagements.</li><li><strong>Legal and regulatory compliance:</strong> Nigerian or international regulators, government authorities, law enforcement agencies or courts where required by law or official mandate.</li><li><strong>Corporate restructuring:</strong> A merger, acquisition, joint venture or sale of assets, subject to confidentiality commitments.</li><li><strong>Protection of rights and system integrity:</strong> Enforcing terms, protecting intellectual property, defending claims or safeguarding systems against cyber threats.</li></ul></Policy>
    <Policy title="International transfers"><p>As a global ESG advisory firm, Terratora may transfer, store or process personal data outside your country of residence, including through secure cloud infrastructure in Europe, the United Kingdom or North America. We ensure transfers comply with the Nigeria Data Protection Act 2023, the Nigeria Data Protection Commission’s General Application and Implementation Directive 2025 and the GDPR where applicable.</p><ul><li><strong>Adequacy and safeguards:</strong> We use approved jurisdictions or appropriate safeguards such as Data Processing Agreements and Standard Contractual Clauses.</li><li><strong>Transfers to other jurisdictions:</strong> Where no adequacy designation exists, we apply supplementary technical measures, such as end-to-end encryption, or rely on explicit informed consent where appropriate.</li></ul></Policy>
    <Policy title="Data retention and security"><p>We retain personal data only as long as necessary for the purpose collected or to satisfy legal, statutory, accounting or regulatory requirements. We consider the amount, nature and sensitivity of the data; the potential risk from unauthorised use; the duration of the business relationship; statutory retention periods; and limitation periods for legal or professional claims.</p><p>When data is no longer required, it is securely deleted, overwritten or irreversibly anonymised. Our organisational, technical and physical controls include secure servers, firewalls, multi-factor authentication, encryption, anonymisation or pseudonymisation where appropriate, and need-to-know access controls.</p></Policy>
    <Policy title="Your rights as a data subject"><p>Under the NDPA and applicable international laws, you may exercise the following rights:</p><ul><li>Access and information about how your data is processed.</li><li>Rectification of inaccurate or incomplete personal data.</li><li>Erasure where no legal or statutory retention duty applies.</li><li>Withdrawal of consent at any time where processing is consent-based.</li><li>Restriction of processing in qualifying circumstances.</li><li>Data portability in a machine-readable format where technically feasible.</li><li>Objection to direct marketing or processing based on legitimate interests.</li><li>Protection from decisions based solely on automated processing or profiling that significantly affect you.</li><li>A complaint to the Nigeria Data Protection Commission at <a href="mailto:info@ndpc.gov.ng">info@ndpc.gov.ng</a>, or to your local data-protection authority.</li></ul><h3>How to exercise your rights</h3><p>Contact our Data Protection Officer at <a href="mailto:privacy@terratoraconsulting.com">privacy@terratoraconsulting.com</a>. We will respond within 30 calendar days in accordance with NDPA guidelines and may need to verify your identity before fulfilling a request.</p></Policy>
    <Policy title="Changes to this Privacy Notice"><p>Terratora may update this notice to reflect changes in the Nigeria Data Protection Act, other regulations, international standards such as GDPR, or our operations and technology. Material changes will be highlighted on the website, reflected in an updated effective date or communicated by email where appropriate. Where a change significantly affects consent-based processing, we will seek fresh consent before it takes effect.</p></Policy>
    <Policy title="Contact our Data Protection Officer"><p>Questions about our collection and processing of personal data or the exercise of your rights under the NDPA or GAID can be sent to <a href="mailto:privacy@terratoraconsulting.com">privacy@terratoraconsulting.com</a>.</p><p>Terratora Limited</p></Policy>
  </div></div></section></>;
}

function Policy({ title, children }: { title: string; children: ReactNode }) {
  return <article data-reveal><h2>{title}</h2>{children}</article>;
}
