import type { Metadata } from "next";
import Link from "next/link";
import type { ReactNode } from "react";
import { CookieSettingsButton } from "@/components/cookie-settings-button";
import { PageHero } from "@/components/page-hero";

export const metadata: Metadata = { title: "Cookie policy" };

export default function CookiesPage() {
  return <><PageHero eyebrow="Browser preferences" title="Cookie policy" lede="How Terratora Limited uses cookies and similar technologies, and how you can manage your choices." image="/images/hero/sustainable-business.jpg" imagePosition="50% 46%" crumbs={[{ label: "Cookie policy" }]} /><section className="policy-page" data-color-flow="aqua"><div className="shell policy-grid"><aside><p>Your controls</p><strong>Manage optional cookies at any time.</strong><CookieSettingsButton /></aside><div className="policy-copy">
    <p className="policy-intro">This Cookie Notice explains how Terratora Limited (“Terratora”, “we”, “us”, or “our”) uses cookies and similar tracking technologies on our website, and how you can manage your cookie preferences. For further details on how we collect, process and protect your personal data, review our <Link href="/privacy">Privacy Notice</Link>.</p>
    <Policy title="What are cookies?"><p>Cookies are small text files stored on your computer or mobile device when you visit a website. They are widely used to make websites work efficiently, enhance user experience and provide analytical insights to site owners.</p><ul><li><strong>Session cookies:</strong> Temporary cookies that expire and are automatically erased when you close your browser.</li><li><strong>Persistent cookies:</strong> Cookies that remain stored on your device for a set period or until you manually delete them, allowing us to remember your preferences for future visits.</li></ul><p>Where cookies collect personal data, we handle that information in full compliance with our Privacy Notice.</p></Policy>
    <Policy title="How Terratora uses cookies"><h3>Strictly Necessary Cookies (Always Active)</h3><p>These cookies are essential for the operation of our website and cannot be switched off in our systems. They enable core functions such as security, network management, accessibility and setting your privacy preferences. You can set your browser to block these cookies, but certain parts of the site may not function properly.</p><p><strong>Legal basis:</strong> Legitimate interest / essential website operation.</p><h3>Functional Cookies (Optional)</h3><p>These cookies allow our website to remember choices you make, such as language preferences or region, and provide enhanced, personalised features. They may be set by us or by third-party service providers whose tools are embedded on our pages.</p><p><strong>Legal basis:</strong> Consent.</p><h3>Performance &amp; Analytics Cookies (Optional)</h3><p>These cookies allow us to count visits and traffic sources so we can measure and improve website performance. They help us understand which pages are popular, how visitors navigate the site and whether errors occur. Data collected through these cookies is aggregated and pseudonymised.</p><p><strong>Legal basis:</strong> Consent.</p></Policy>
    <Policy title="Third-party facilities and information sharing"><p>Our website may include embedded third-party content, plugins or applications, such as social-media share buttons or hosted video clips. When you interact with these features or accept Functional or Marketing cookies, third-party providers may collect or share data about your browsing behaviour.</p><p>You can manage or revoke consent for third-party tracking at any time through our Cookie Preference Centre.</p></Policy>
    <Policy title="How to manage and reject cookies"><h3>Cookie Preference Centre (recommended)</h3><p>You can customise, grant or revoke cookie preferences at any time by selecting Cookie Settings in the footer of every page. This lets you switch non-essential Functional, Performance and Marketing cookies on or off individually.</p><h3>Browser settings</h3><p>Most browsers let you refuse cookies, prompt before accepting a cookie or delete stored cookies. Consult your browser’s help menu for instructions. Disabling strictly necessary cookies through browser settings may affect your experience and restrict certain features.</p></Policy>
    <Policy title="Terratora active cookie list"><ul><li><strong>Essential services:</strong> Tools required for basic website operation, security and storing consent preferences.</li><li><strong>First-party site analytics:</strong> Pseudonymised visit and page-view reporting that helps us understand traffic, popular pages and the overall user experience.</li><li><strong>Professional network analytics (LinkedIn):</strong> Tools used to measure the effectiveness of B2B content and corporate announcements.</li></ul></Policy>
  </div></div></section></>;
}

function Policy({ title, children }: { title: string; children: ReactNode }) {
  return <article data-reveal><h2>{title}</h2>{children}</article>;
}
