create table if not exists public.site_page_views (
  id bigint generated by default as identity primary key,
  session_id text not null check (char_length(session_id) between 1 and 100),
  visitor_id text not null check (char_length(visitor_id) between 1 and 100),
  path text not null check (char_length(path) between 1 and 300),
  viewed_at timestamptz not null default now()
);

create index if not exists site_page_views_viewed_at_idx
  on public.site_page_views (viewed_at desc);
create index if not exists site_page_views_path_idx
  on public.site_page_views (path);
create index if not exists site_page_views_session_idx
  on public.site_page_views (session_id);

alter table public.site_page_views enable row level security;

create or replace function public.get_site_analytics()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'total_visits', (select count(distinct session_id) from public.site_page_views),
    'total_page_views', (select count(*) from public.site_page_views),
    'unique_visitors', (select count(distinct visitor_id) from public.site_page_views),
    'views_this_month', (
      select count(*)
      from public.site_page_views
      where viewed_at >= date_trunc('month', now())
    ),
    'months', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'month', to_char(month_start, 'YYYY-MM'),
          'page_views', page_views,
          'visits', visits
        ) order by month_start
      )
      from (
        select
          month_start,
          count(page_view.id) as page_views,
          count(distinct page_view.session_id) as visits
        from generate_series(
          date_trunc('month', now()) - interval '5 months',
          date_trunc('month', now()),
          interval '1 month'
        ) as month_start
        left join public.site_page_views as page_view
          on page_view.viewed_at >= month_start
          and page_view.viewed_at < month_start + interval '1 month'
        group by month_start
      ) as monthly_totals
    ), '[]'::jsonb),
    'top_pages', coalesce((
      select jsonb_agg(to_jsonb(page_totals) order by page_views desc, path)
      from (
        select
          path,
          count(*) as page_views,
          count(distinct session_id) as visits
        from public.site_page_views
        group by path
        order by page_views desc, path
        limit 10
      ) as page_totals
    ), '[]'::jsonb)
  );
$$;

revoke all on table public.site_page_views from public, anon, authenticated;
revoke all on function public.get_site_analytics() from public, anon, authenticated;
grant all on table public.site_page_views to service_role;
grant usage, select on sequence public.site_page_views_id_seq to service_role;
grant execute on function public.get_site_analytics() to service_role;
